#%RAML 1.0 NamedExample
value:
  - ID: CO-001
    creationDate: 2018-01-01
    firstName: Jorge
    middleName: Luis
    lastName: Ramos
    email: jramos@avanxo.com
    reportsTo: US-001
    isActive: true
    userId: US-100

  - ID: CO-002
    creationDate: 2018-01-01
    firstName: Rodrigo
    middleName: Fernando
    lastName: Resendiz
    email: jresendiz@avanxo.com
    reportsTo: US-002
    isActive: true
    userId: US-200

  - ID: CO-003
    creationDate: 2018-01-01
    firstName: Pablo
    middleName: Andres
    lastName: Bogota
    email: pbogota@avanxo.com
    reportsTo: US-003
    isActive: true
    userId: US-001


  - ID: CO-004
    creationDate: 2018-01-01
    firstName: Harold
    middleName: Didier
    lastName: Tamayo
    email: htamayo@avanxo.com
    reportsTo: US-003
    isActive: true
    userId: US-002
