#%RAML 1.0 NamedExample
value:

  - ID: US-001
    creationDate: 2018-01-01
    firstName: Pablo
    middleName: Andres
    lastName: Bogota
    email: pbogota@avanxo.com
    userName: pbogota@avanxo.com
    isActive: true

  - ID: US-002
    creationDate: 2018-01-01
    firstName: Harold
    middleName: Didier
    lastName: Tamayo
    email: htamayo@avanxo.com
    userName: htamayo@avanxo.com
    isActive: true

  - ID: US-003
    creationDate: 2018-01-01
    firstName: Tharren
    middleName: J
    lastName: Clark
    email: tclark@acumensolutions.com
    userName: tclark@acumensolutions.com
    isActive: true

  - ID: US-100
    creationDate: 2018-01-01
    firstName: Jorge
    middleName: Luis
    lastName: Ramos
    email: jramos@avanxo.com
    userName: jramos@avanxo.com
    isActive: true

  - ID: US-200
    creationDate: 2018-01-01
    firstName: Rodrigo
    middleName: Fernando
    lastName: Resendiz
    email: rresendiz@avanxo.com
    userName: rresendiz@avanxo.com
    isActive: true