#%RAML 1.0 NamedExample
value:
  ID: US-001
  creationDate: 2018-01-01
  firstName: Pablo
  middleName: Andres
  lastName: Bogota
  email: pbogota@avanxo.com
  userName: pbogota@avanxo.com
  isActive: true
